import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export interface SrcCommandResult {
  success: boolean;
  code: number;
  stdout: string;
  stderr: string;
}

export function runSrcCli(args: string[], cwd = process.cwd()): Promise<SrcCommandResult> {
  return new Promise(resolve => {
    const child = spawn('src', args, {
      cwd,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: process.env
    });

    let stdout = '';
    let stderr = '';

    child.stdout.on('data', chunk => { stdout += String(chunk); });
    child.stderr.on('data', chunk => { stderr += String(chunk); });

    child.on('error', error => {
      resolve({
        success: false,
        code: 1,
        stdout,
        stderr: `${stderr}${error.message}`
      });
    });

    child.on('close', code => {
      resolve({
        success: code === 0,
        code: code ?? 1,
        stdout,
        stderr
      });
    });
  });
}

export interface SrcBatchPlanOptions {
  query: string;
  repos: string[];
  execute?: boolean;
  specPath?: string;
}

export async function createSrcBatchPlan(options: SrcBatchPlanOptions, cwd = process.cwd()): Promise<{
  success: boolean;
  specPath: string;
  message: string;
}> {
  if (!options.query) {
    return { success: false, specPath: '', message: 'Missing --query for batch-plan' };
  }

  const repos = options.repos.length ? options.repos : ['repo:^github\\.com/.+'];
  const specPath = options.specPath || '.crew/src-batch.spec.yaml';
  const full = join(cwd, specPath);
  await mkdir(join(full, '..'), { recursive: true });

  const yaml = [
    'name: crew-src-batch-plan',
    'description: Generated by crew src batch-plan',
    `on: ${repos[0]}`,
    'steps:',
    `  - run: |`,
    `      # Replace with desired codemod command`,
    `      src search '${options.query.replace(/'/g, "\\'")}'`,
    '',
    'changesetTemplate:',
    '  title: "chore: planned codemod"',
    '  body: |',
    '    Generated by `crew src batch-plan` in dry-run mode.'
  ].join('\n');

  await writeFile(full, `${yaml}\n`, 'utf8');

  if (!options.execute) {
    return {
      success: true,
      specPath: full,
      message: `Batch plan created at ${full}. Dry-run only. Execute with: src batch preview -f ${full}`
    };
  }

  const preview = await runSrcCli(['batch', 'preview', '-f', full], cwd);
  if (!preview.success) {
    return { success: false, specPath: full, message: preview.stderr || 'src batch preview failed' };
  }
  return { success: true, specPath: full, message: 'src batch preview succeeded' };
}
